### ISSUE TITLE
Minor Problems

### ISSUE THREAD

**Issue by lilys012** [swsnu/swppfall2022-team6#120]
### Todo

- [x] 1 로딩할 때 디폴트 화면 없애기
- [x] 2 현재 위치, 시간 반영하기 -> 시간은 보류
- [x] 3 adjust back button urls
- [x] 4 사진 용량 조절
- [x] 5 포스트 로케이션
- [x] 6 hashfeed undeifined
- [x] 7 Main Page Map level - 원 다 보이게 조정하기
- [x] 8 Max length 설정
- [x] #122
- [x] 10 사인업/사인인 관련 문제들 : email validation 실패 시 존재하는 이메일이라고 뜸, 로그인 실패시 alert
- [x] 11 url에 잘못 입력된 params 입력하면 redirect
- [ ] 12 튜토리얼 (Feedback: 태그 등록, 다답글 보기, 날씨 리포트와 포스트의 구분)
- [x] 13 svg 아이콘 오류들 -> 로컬에서는 잘 되는 것으로 확인
- [x] 14 포스트 글 줄바꿈 -> 로컬에서는 잘 되는 것으로 확인
- [x] 15 장소 검색 시 존재하지 않으면 alert가 두번 / error가 나기도 함
- [x] 16 2시간 경과시 로그아웃 alert 네번, areafeed 같은 페이지에서는 그냥 unauthorized -> 자동 logout 안됨
- [x] 17 뱃지 achieve
- [x] 18 Signin에서 뒤로가기가 막혀있는지? -> 로컬에서는 잘 되는 것으로 확인
- [x] 19 날씨 아이콘 잘림
- [x] 20 happy 이외의 단어선택

### Feedbacks
- [ ] 1 한국 외의 지역 처리
- [ ] 2 회원가입 후 바로 로그인
- [ ] 3 글 삭제
- [x] 4 뱃지 잠금
- [ ] 5 장소 즐겨찾기
- [x] 6 에리아피드에서 최대 n개의 게시물만 보여지기
- [x] 7 쓴 리포트 모아보기

**Comment by lilys012** [comment]
We decided to not implement uncovered todos and leave as future works.
