### ISSUE TITLE
Statistics

### ISSUE THREAD

**Issue by lilys012** [swsnu/swppfall2022-team6#41]
### Todo

- [x] 1 Show pie graph of weather
- [x] 2 Show bar graph of reports
- [x] 3 Develop backend API (Report.GET)
